# Refresh interval in minutes
interval: 60

# Text to add to the bot profile befor the list of subscribed servers
profile_prefix: "I am boosting trending posts from:"

# profile fields to fill in
fields:
  code: https://github.com/tante/hype
  operator: "YOUR HANDLE HERE"

# Define subscribed instances and
# their individual limit (top n trending posts)
# which is again limited by the API to max 20
subscribed_instances:
  chaos.social:
    limit: 5
  mastodon.social:
    limit: 5

# Posts originating from filtered instances will never be reposted.
# The filter checks for the instance of the original posting account, not the
# server that marked it as a popular post.
# This can be used to filter out abusive instances as well as protect small
# instances who could be overwhelmed with a repost to a significant amount of
# other instances
filtered_instances:
